### ISSUE TITLE
Steps to Complete for Upcoming Release

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#76]
# Items Needed to Finish Release - This list is a work in progress

**Development Items:** A list of tasks that are still needed to wrap up development.

- [x] Need replacement font for character sheet name/title - see #72 
- [x] Finish update for Languages - see #79 
- [x] Compendium Rework
   - [x] Rename and change the organizational structure for compendia - In progress
- [x] Fix NPC Health - see #74 - this is a pull request, see https://github.com/AutarchLLC/foundryvtt-acks-core/pull/75
- [x] Investigate newly reported issue and fix, if simple update - see #77 

**Documentation Needed:** A list of tasks to prep for the release.

- [x] Write an Upgrade Guide to describe how to update to the new version.
   - [x] List / describe the items that will be affected during the update
   - [x] List the data that you should check, and what other conditions to verify, after updating.
- [x] ~~Write a How-To to describe how to use the new Languages implementation~~
- [x] ~~Write a How-To that describes how to use the new Hirelings implementation~~
- [x] Write the Release Notes and Changelog

**Quality Checks:** A list of revised features that need to be checked (or re-checked).

- [x] Check that the list of Languages is complete and has no spelling errors.
see #70 
see #79 
- [x] Check the Combat tracker to confirm that the initiative rolling and turn tracker does not have the problem that Archon reported. Also, the speed should be improved.
- [x] Finish testing Hireling edge-cases to eliminate bugs.
- [x] ~~Test active-effects and confirm they work.~~
- [x] Retest item weights - spikes, torches, arrows, other - see #73 
- [x] Re-test and close as many issues as we can - review the open issues starting from issue 63 and onward.

**Deferred from this release**
There are several things that will go into the next release.

- [x] See issue #82 

# Documentation Notes

**New Features Added**
* Languages: Added compendium of Languages which can be extended.
* Money: Added compendium of currency types (Coins) which can be extended.
* Hirelings: Added new character sheet tab for Hirelings.
* Active Effects: Added new character sheet tab for Active Effects.
* Encumbrance: Now calculated in Stone and Item.
* todo

**Improvements and Updates Made**
* Improved the initiative-order sorting for combat tracker
* Converted all weights to stones.
* Modified the weight tracking for consumables like arrows, spikes, torches.

**Comment by ArcanistWill** [comment]
Completed (mostly)! Closing
