### ISSUE TITLE
Language items

### ISSUE THREAD

**Issue by ArcanistWill** [AutarchLLC/foundryvtt-acks-core#79]
Some notes for the Languages support. 

**To-Do**
- [x] One language is missing and needs to be added to the list before final release: **Argollëan**.  No need to rebuild the pack just yet.
- [x] Update the Language items (generate the new ones)
- [x] Regenerate the equipment pack with all Language items.

**Nothing to do for these yet**

- [x] There are many other languages listed in the rules, like Ancient forms of the modern language name, but I don't know if we need to add everything from the rules. I will find out.
- [x] I'm not excited about the icon used for the languages. Will need to see if there is something better.

**Comment by ArcanistWill** [comment]
Done. Closing!
